# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 496a595e00e84892be7e97515206ea8d3bd75e1fa73a50628167ddeebd9039d50bcd1a8e17301228cedd9526becf9e9c81b3bb2facffacf105e3e27d5a8e23bb

test:
  secret_key_base: 44449e0a41554198439fbaa533df92321ccace50dd46b3a1190340cc51530bd449db7ac4082628cefd9199b248f523dc28abcdfbf36675a431404057a8c8a2e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
